### ISSUE TITLE
Iteration 1 - one test has error

### ISSUE THREAD

**Issue by jbrucker** [Isolation666/ku-polls#2]
Output of "manage.py test polls" based on code pulled 6 Sep.

======================================================================
ERROR: test_past_question (polls.tests.QuestionDetailViewTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/submit/ISP/Noppharut/ku-polls/polls/tests.py", line 126, in test_past_question
    response = self.client.get(url)
  File "/usr/local/lib/python3.6/dist-packages/django/test/client.py", line 742, in get
    response = super().get(path, data=data, secure=secure, **extra)
  File "/usr/local/lib/python3.6/dist-packages/django/test/client.py", line 398, in get
    **extra,
  File "/usr/local/lib/python3.6/dist-packages/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/usr/local/lib/python3.6/dist-packages/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/usr/local/lib/python3.6/dist-packages/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.6/dist-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.6/dist-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/usr/local/lib/python3.6/dist-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/usr/local/lib/python3.6/dist-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.6/dist-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.6/dist-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.6/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/local/lib/python3.6/dist-packages/django/template/loaders/cached.py", line 58, in get_template
    template = super().get_template(template_name, skip)
  File "/usr/local/lib/python3.6/dist-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.6/dist-packages/django/template/defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' loop.counter' from 'for loop.counter'

----------------------------------------------------------------------
Ran 10 tests in 0.085s

FAILED (errors=1)

**Comment by NoppharutKDS** [comment]
Fix error by change from for loop.counter into forloop.counter in detail.html
